### ISSUE TITLE
Rename Package Name

### ISSUE THREAD

**Issue by yannik1015** [bkogler/goecharger-api-lite#3]
Is it possible to rename the package name used for importing? The currently used `import goecharger` conflicts with the geocharger package https://pypi.org/project/goecharger/, which works on the v1 of the API. As they work on API version 1 and 2 respectively there is a high possibility of both packages being used in the same program.

**Comment by ghubrakesh** [comment]
you can use the `importlib` python module to import a specific version dynamically. But this will make code complex, so you need to take care of it.

**Comment by yannik1015** [comment]
I don't think this is possible as the `goecharger-api-lite` package installs itself in the `site-packages/goecharger` folder which is the same as the `goecharger` package. Therefore depending on the installation order of the two packages this folder will overwrite the others. At least this is what I think happens here.

**Comment by bkogler** [comment]
Thanks for your suggestion, renaming package name seems to be quite useful. Released in version 1.5.0
